### ISSUE TITLE
Add other lifecycle hooks to ViewModel Options API

### ISSUE THREAD

**Issue by jukieb0x** [Lumkani/vue-view-model-api#4]
There is no automatic injection of hook functions other than the `mounted` hook.

Currently we can specify the method for the mounted lifecycle hook in JS without having to write anything in our Vue component:
```javascript 
class TextViewModel {
  static data = () => ({
    text: null
  })
  
  static mounted = async (vm) => {
    const textData = await someAPI()
    
    vm.text = textData
  }
}
```

Other lifecycle hooks and navigation guard hooks such as `created`, `destroyed` and `beforeRouteLeave` still need to be declared in the format:

```vue
<script>
import {LayoutModel as ViewModel } from './model'

export default {
  name: 'MyLayout',
  beforeRouteUpdate(to, from, next) {
    ViewModel.beforeRouteUpdate(this, { to, from, next })
  },
  ViewModel,
}
</script>
```

**Comment by ShailenNaidoo** [comment]
Added these features in release #5
